export const ACTIONS = {
  GET_PRODUCTS: "GET_PRODUCTS",
  GET_PRODUCT_DETAILS: "GET_PRODUCT_DETAILS",
  GET_CART: "GET_CART",
  CHANGE_CART_LENGTH: "CHANGE_CART_LENGTH",
  GET_FAVS: "GET_FAVS",
  CHANGE_FAVS_LENGTH: "CHANGE_FAVS_LENGTH",
  GET_COMMENTS: "GET_COMMENTS",
};

export const ADMIN = "aijan@gmail.com";

export const JSON_API_PRODUCTS = "http://localhost:8000/creatures";

export const PRODUCT_LIMIT = 8;
